[package]
name = "pr_trigger_discord_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.37.0"
serenity = "0.12.1"
tokio = "1.37.0"
